services:
  postgres:
    image: postgres
    container_name: todo-db
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todo_db
    restart: always

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - '8081:8080'

volumes:
  postgres: